[
  #  ./theme.nix
  ./applications/_1password.nix
  ./applications/alacritty.nix
  ./applications/firefox.nix
  ./applications/gnupg.nix
  ./applications/neovim.nix
  ./applications/steam.nix
  ./applications/vscode.nix
  ./autoupgrade.nix
  ./development
  ./graphics
  ./home-server
  ./networking
  ./options.nix
  ./profiles/base.nix
  ./profiles/server.nix
  ./profiles/webserver.nix
  ./security
  ./shell
]
