keys:
  - &user_gabehoban 3EADE0CB32D1BC80DF96F538AFD8F294983C4F95
  - &host_baymax age109yhtevy5nmrhalezclagwf02v45xhfwn796aag779w2ff8c05nsjljwy8
  - &host_casio age14wfccms9xweg7wkvstm63lxsf3smlczphs92hmj2q8945ay8aejs2kaepl
  - &host_sekio age13u78nx6tj3fwshqtxp3qklrrpuusmujqqclnsnlazajtr76h6qaqdhlrhe
  - &host_vpsio age1a6hxurcnu3agwduea6e63hpk2w7fll0k3vf84ljugtmh8yjqd9hqfvf2aw
  - &host_srvio age12m3xc69afdu02u7agx26f4qhav8rphwd68ax6v5tydjj4tsuvqaqzle2sx
creation_rules:
  - path_regex: secrets/[^/]+\.(yaml|json|env|ini)$
    key_groups:
      - pgp:
        - *user_gabehoban
        age:
        - *host_baymax
        - *host_casio
        - *host_sekio
        - *host_vpsio
        - *host_srvio
