[package]
name = "gpsd_exporter"
description = "Prometheus exporter for GPSD metrics."
version = "0.1.0"
edition = "2021"

[features]
default = []
serialize = [] # Enable Serde Serialize for the types

[dependencies]
env_logger = "0.11.5"
gpsd_proto = "1.0.0"
hyper = { version = "0.14.28", features = ["full"] }
lazy_static = "1.5.0"
log = "0.4.22"
prometheus = "0.13.4"
serde = "1.0"
serde_derive = "1.0"
serde_json = "1.0"
tokio = { version = "1.37.0", features = ["full"] }

[[bin]]
name = "gpsd-exporter"
path = "main.rs"
