{ config, pkgs, inputs, lib, ... }:
let
  inherit (inputs)
    self
    nixos-hardware
    home-manager
    impermanence
    ;
in
{
  imports =
    (lib.singleton ./hardware-configuration.nix)
    ++ (lib.attrValues {
      inherit (impermanence.nixosModules) impermanence;
      inherit (home-manager.nixosModules) home-manager;
      inherit (nixos-hardware.nixosModules)
        raspberry-pi-4
        ;
      inherit (self.nixosModules)
        common-home-manager
        common-nix
        common-packages
        common-shell
        common-zram
        ;
    });

  networking.hostName = "rpi-sekio";

  # Bootloader
  boot.loader.efi.canTouchEfiVariables = true;
  boot.loader.timeout = 0;
  boot.loader.grub.enable = false;
  boot.loader.generic-extlinux-compatible.enable = true;

  hardware = {
    raspberry-pi."4".apply-overlays-dtmerge.enable = true;
    deviceTree = {
      enable = true;
      filter = "*rpi-4-*.dtb";
    };
  };

  environment.systemPackages = with pkgs; [
    libraspberrypi
    raspberrypi-eeprom
  ];

  # systemd.services.NetworkManager-wait-online.enable = false;
  systemd.network.wait-online.enable = false;

  networking.useDHCP = lib.mkDefault true;
  nix.settings.max-jobs = 4;

  time.timeZone = "America/New_York";

  users.groups = {
    "sysadmin" = {};
    dialout = {};
    uinput  = {};
  };

  users.users."sysadmin" = {
    # generated by `mkpasswd -m scrypt`
    # we have to use initialHashedPassword here when using tmpfs for /
    initialHashedPassword = "$7$CU..../....4pm.YfTlZIn3yxrWDiSiZ.$x0dbd35YvFAEy8F3prOHZFBXmlt4srxgvnyjxAAtae4";
    home = "/home/sysadmin";
    isNormalUser = true;
    extraGroups = [
      "sysadmin"
      "users"
      "networkmanager"
      "wheel"
    ];
    openssh.authorizedKeys.keys = [
      "ssh-rsa AAAAB3NzaC1yc2EAAAADAQABAAACAQCqFRwe/auSdigp5l+XmgIABl8rIIFuwBh9I2WNRpIfYKYJRyKkLbYZO3Z56lCxqjJkTUIIdw+hsUvR3A71HVRnRlx05pMQ9IMn6XSrx+AQVXs/hBFNijQsmCVUMebop2kW1WZUfIgMg4+5L9VQPL+pX6ARKuXSf8Gv2Qn+rInpY1rYE9DesezjzA2Cljr3Pii1JlmqYDDLS2HnZ10FhJfutqWPUR9RnX4HcVXKcxE9rgHzjGSyNkaFVX2HG8SafePyABacoajNQVORn7PHD9RLUeQ+qM8IIvAVxig2JPt36AnWjakSumwgyf/NjrbjJTMlacN3zqresfcsa3+HdGki86QRbZ2bNRurrBbevxxzgQggjW0506drw49sN/y78BGuYjZJjQW3C7TPHaLpPBKMIEFz64vuwATZiLpSb/mfGqXvpXb9Yl91qYbOy6GdXOO54EMb4zM6pQn1n3h6uaneJ/ZjM2GarbcGE5d/Nxw3AsS7gVUBAXrkbHdmJnXzoZWKO1DGjx7fGnHHvyKZN997BEzGpTMIRbF7g2S0RLVVjVYmLJNpCPGxkWACeJN+CXYof/Yl1adeCmQVLagtO8HwsBQLRO2CJwveUwnNRK3WVOOM8DK+u5ROgg1XJO7ngXnP3HKql6ju0kYRpwlRj/dZNrsJh7tYDgXr/9B8I/9Q4w== cardno:17_077_465"
    ];
  };
  users.users.root = {
    initialHashedPassword = config.users.users."sysadmin".initialHashedPassword;
    openssh.authorizedKeys.keys = config.users.users."sysadmin".openssh.authorizedKeys.keys;
  };

  environment.persistence."/persistent" = {
    hideMounts = true;
    directories = [
      "/etc/NetworkManager/system-connections"
      "/etc/ssh"
      "/etc/nix/inputs"
      "/etc/secureboot" # lanzaboote - secure boot

      # my secrets
      "/etc/agenix/"

      "/var/log"
      "/var/lib"
    ];
    files = [
      "/etc/machine-id"
    ];

    # the following directories will be passed to /persistent/home/$USER
    users.sysadmin = {
      directories = [
        "nix-config"
        {
          directory = ".gnupg";
          mode = "0700";
        }
        {
          directory = ".ssh";
          mode = "0700";
        }
        # misc
        ".pki"
        # neovim / remmina / flatpak / ...
        ".local/share"
        ".local/state"
      ];
    };
  };

  home-manager.users.sysadmin = import ./home.nix;
  system.stateVersion = "24.05";
}
