{
  config,
  inputs,
  lib,
  ...
}:
let
  inherit (inputs)
    self
    nixos-hardware
    home-manager
    lanzaboote
    impermanence
    ;
in
{
  imports =
    (lib.singleton ./hardware-configuration.nix)
    ++ (lib.attrValues {
      inherit (lanzaboote.nixosModules) lanzaboote;
      inherit (impermanence.nixosModules) impermanence;
      inherit (home-manager.nixosModules) home-manager;
      inherit (nixos-hardware.nixosModules) common-pc-ssd;
      inherit (self.nixosModules)
        common-home-manager
        common-nix
        common-packages
        common-shell
        common-zram

        gui-gaming
        gui-gnome
        gui-misc
        gui-nvidia
        gui-pipewire
        ;
    });

  networking.hostName = "baymax";

  # Bootloader
  boot.loader.efi.canTouchEfiVariables = true;
  boot.lanzaboote = {
    enable = true;
    pkiBundle = "/etc/secureboot";
  };
  boot.loader.timeout = 0;
  boot.initrd.systemd.enable = true;

  # dbus-broker is more performant
  services.dbus.implementation = "broker";

  # systemd.services.NetworkManager-wait-online.enable = false;
  systemd.network.wait-online.enable = false;

  networking.useDHCP = lib.mkDefault true;
  nix.settings.max-jobs = 4;

  time.timeZone = "America/New_York";

  users.groups = {
    "gabehoban" = { };
    docker = { };
    dialout = { };
    # for openocd (embedded system development)
    plugdev = { };
    # misc
    uinput = { };
  };

  users.users."gabehoban" = {
    # generated by `mkpasswd -m scrypt`
    # we have to use initialHashedPassword here when using tmpfs for /
    initialHashedPassword = "$7$CU..../....4pm.YfTlZIn3yxrWDiSiZ.$x0dbd35YvFAEy8F3prOHZFBXmlt4srxgvnyjxAAtae4";
    home = "/home/gabehoban";
    isNormalUser = true;
    extraGroups = [
      "gabehoban"
      "users"
      "networkmanager"
      "wheel"
      "docker"
      "libvirtd"
    ];
    openssh.authorizedKeys.keys = [
      "ssh-rsa AAAAB3NzaC1yc2EAAAADAQABAAACAQCqFRwe/auSdigp5l+XmgIABl8rIIFuwBh9I2WNRpIfYKYJRyKkLbYZO3Z56lCxqjJkTUIIdw+hsUvR3A71HVRnRlx05pMQ9IMn6XSrx+AQVXs/hBFNijQsmCVUMebop2kW1WZUfIgMg4+5L9VQPL+pX6ARKuXSf8Gv2Qn+rInpY1rYE9DesezjzA2Cljr3Pii1JlmqYDDLS2HnZ10FhJfutqWPUR9RnX4HcVXKcxE9rgHzjGSyNkaFVX2HG8SafePyABacoajNQVORn7PHD9RLUeQ+qM8IIvAVxig2JPt36AnWjakSumwgyf/NjrbjJTMlacN3zqresfcsa3+HdGki86QRbZ2bNRurrBbevxxzgQggjW0506drw49sN/y78BGuYjZJjQW3C7TPHaLpPBKMIEFz64vuwATZiLpSb/mfGqXvpXb9Yl91qYbOy6GdXOO54EMb4zM6pQn1n3h6uaneJ/ZjM2GarbcGE5d/Nxw3AsS7gVUBAXrkbHdmJnXzoZWKO1DGjx7fGnHHvyKZN997BEzGpTMIRbF7g2S0RLVVjVYmLJNpCPGxkWACeJN+CXYof/Yl1adeCmQVLagtO8HwsBQLRO2CJwveUwnNRK3WVOOM8DK+u5ROgg1XJO7ngXnP3HKql6ju0kYRpwlRj/dZNrsJh7tYDgXr/9B8I/9Q4w== cardno:17_077_465"
    ];
  };
  users.users.root = {
    inherit (config.users.users."gabehoban") initialHashedPassword;
    openssh.authorizedKeys.keys = config.users.users."gabehoban".openssh.authorizedKeys.keys;
  };

  environment.persistence."/persistent" = {
    hideMounts = true;
    directories = [
      "/etc/NetworkManager/system-connections"
      "/etc/ssh"
      "/etc/nix/inputs"
      "/etc/secureboot" # lanzaboote - secure boot

      # my secrets
      "/etc/agenix/"

      "/var/log"
      "/var/lib"
    ];
    files = [ "/etc/machine-id" ];

    # the following directories will be passed to /persistent/home/$USER
    users.gabehoban = {
      directories = [
        "nix-config"

        "Downloads"
        "Music"
        "Pictures"
        "Documents"
        "Videos"
        "DevOps"

        {
          directory = ".gnupg";
          mode = "0700";
        }
        {
          directory = ".ssh";
          mode = "0700";
        }

        # misc
        ".config/pulse"
        ".pki"
        ".steam"

        # cloud native
        {
          # pulumi - infrastructure as code
          directory = ".pulumi";
          mode = "0700";
        }

        # remote desktop
        ".config/remmina"

        # 1Password
        ".config/1Password"

        # Discord
        ".config/discord"

        # vscode
        ".vscode"
        ".vscode-insiders"
        ".config/Code/User"
        ".config/Code - Insiders/User"

        # browsers
        ".mozilla"

        # neovim / remmina / flatpak / ...
        ".local/share"
        ".local/state"
      ];
      files = [ ".config/nushell/history.txt" ];
    };
  };

  home-manager.users.gabehoban = import ./home.nix;
  system.stateVersion = "24.05";
}
